BEGIN;

DROP TABLE IF EXISTS "user", "zone", "vegetable", "family", "task";

CREATE TABLE IF NOT EXISTS "user" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "email" TEXT NOT NULL UNIQUE,
    "password" TEXT NOT NULL,
    "first_name" TEXT,
    "last_name" TEXT,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "zone" ( 
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "user_id" INTEGER NOT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP,
    FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE
    

);

CREATE TABLE IF NOT EXISTS "family" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "soil_type" TEXT NOT NULL,
    "vegetable_type" TEXT NOT NULL,
    "watering" TEXT NOT NULL,
    "weeding" TEXT NOT NULL,
    "emergence" INTEGER,
    "depth" TEXT,
    "spacing" TEXT,
    "row_spacing" TEXT,
    "exposure" TEXT,
    "start_date_day_seeding" INTEGER,
    "start_date_month_seeding" INTEGER,
    "end_date_day_seeding" INTEGER,
    "end_date_month_seeding" INTEGER,
    "start_date_day_planting" INTEGER NOT NULL,
    "start_date_month_planting" INTEGER NOT NULL,
    "end_date_day_planting" INTEGER NOT NULL,
    "end_date_month_planting" INTEGER NOT NULL,
    "start_date_day_harvest" INTEGER NOT NULL,
    "start_date_month_harvest" INTEGER NOT NULL,
    "end_date_day_harvest" INTEGER NOT NULL,
    "end_date_month_harvest" INTEGER NOT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "vegetable" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "growth_time" INTEGER NOT NULL,
    "variety" TEXT,
    "comment" TEXT,
    "zone_id" INTEGER NOT NULL,
    "family_id" INTEGER NOT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP,
    FOREIGN KEY ("zone_id") REFERENCES "zone" ("id") ON DELETE CASCADE,
    FOREIGN KEY ("family_id") REFERENCES "family" ("id")
);

CREATE TABLE IF NOT EXISTS "task" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "type" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "start_date_period" DATE,
    "end_date_period" DATE,
    "effective_date" DATE,
    "comment" TEXT,
    "vegetable_id" INTEGER NOT NULL,
    FOREIGN KEY ("vegetable_id") REFERENCES "vegetable" ("id") ON DELETE CASCADE,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP
);


COMMIT;


